# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a97be4323320f99fa8865b745078cbb7921268857876e734585f64b941898cf4872b86f448f6c3a23275f2898064bbcadea81a20c57ffe1b825ce4c1ae30bca4

test:
  secret_key_base: 80196f5fa49ee5b4673ea3d8618b370b1834134011daf82b94271262967bebdc8cfc78c8a97d0d41ff526763565dd538eabdde6069c938040a9baedd99098dfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
